### ISSUE TITLE
UploadImage Example doesnt work

### ISSUE THREAD

**Issue by pleinx** [mgp25/Instagram-API#1087]
Hey guys,

i got the following error from script:

```
Notice: Trying to get property of non-object in D:\web\htdocs\projects\a1\src\http\HttpInterface.php on line 198
POST: qe/sync/ DATA: ig_sig_key_version=4&signed_body=2f7693b5b3d577013b964bcfc494ac53701892c71772786e71b99ed7e13a9992.{"id":"cf537b7f-b688-4b79-b7ae-a1474e9d8680","experiments":"ig_android_background_phone_confirmation_v2,ig_android_confirmation_code_registration,ig_android_non_fb_sso,ig_android_sms_consent_in_reg,ig_android_analytics_data_loss,ig_fbns_blocked,ig_android_gmail_oauth_in_reg,ig_android_show_password_in_reg_universe,ig_android_reg_inline_errors,ig_fbns_push,ig_android_gmail_oauth_in_access,ig_android_reg_whiteout_redesign_v2,ig_android_phoneid_sync_interval,ig_android_access_redesign,ig_android_link_to_access_if_email_taken_in_reg"} ← 400 48B RESPONSE: {"status": "fail", "message": "invalid request"} 
Fatal error: Uncaught Error: Call to a member function getIterator() on null in D:\web\htdocs\projects\a1\src\http\HttpInterface.php:635 Stack trace: #0 D:\web\htdocs\projects\a1\src\Instagram.php(2707): InstagramAPI\HttpInterface->api('qe/sync/', 'ig_sig_key_vers...', true, false) #1 D:\web\htdocs\projects\a1\src\Instagram.php(437): InstagramAPI\Request->getResponse(Object(InstagramAPI\SyncResponse)) #2 D:\web\htdocs\projects\a1\src\Instagram.php(314): InstagramAPI\Instagram->syncFeatures(true) #3 D:\web\htdocs\projects\a1\examples\uploadPhoto.php(26): InstagramAPI\Instagram->login() #4 {main} thrown in D:\web\htdocs\projects\a1\src\http\HttpInterface.php on line 635
```

What im doing wrong?

Here the script (from your examples):

```
<?php


include __DIR__.'/../vendor/autoload.php';

require '../src/Instagram.php';

/////// CONFIG ///////
$username = 'FOO';
$password = 'BAR';
$debug = true;
$truncatedDebug = false;

$photo = dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test.png';     // path to the photo
$caption = 'justAtest';     // caption
//////////////////////

$i = new \InstagramAPI\Instagram($username, $password, $debug);
try{
    $i->login();
} catch (\InstagramAPI\InstagramException $e)
{
    $e->getMessage();
    exit();
}
try {
    $i->uploadTimelinePhoto($photo, $caption);
} catch (Exception $e)
{
    echo $e->getMessage();
}
```

Can anyone help?

**Comment by pleinx** [comment]
"Fixt" it. Example was
