### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function InstagramAPI\exif_read_data() in ImageAutoResizer.php:268

### ISSUE THREAD

**Issue by kholmukhamedovme** [mgp25/Instagram-API#1108]
### Before submitting an issue made sure I have:
- [X] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [X] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [X] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [X] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [X] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of my issue
- [X] Bug report (encountered problems/errors)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Bug report

Code:

```php
require("./vendor/autoload.php");

$instagram = new \InstagramAPI\Instagram(true, false);

// Logging in to Instagram
try {
    $instagram -> setUser($account["username"], $account["password"]);
    $instagram -> login();
} catch (Exception $exception) {
    $exception -> getMessage();
    exit();
}

// Uploading content
try {
    // Matching publication type and then deleting file
    if (file_exists($directory_path.$filename)) {
        if ($filename_format == "mp4")
            $instagram -> uploadTimelineVideo($directory_path.$filename, $caption);
        elseif ($filename_format == "jpg")
            $instagram -> uploadTimelinePhoto($directory_path.$filename, $caption);

        unlink($directory_path.$filename);
    }
} catch (Exception $exception) {
    echo $exception -> getMessage();
    exit();
}
```

Log:

```php
Fatal error: Uncaught Error: Call to undefined function InstagramAPI\exif_read_data() in /var/www/html/vendor/mgp25/instagram-php/src/ImageAutoResizer.php:268
Stack trace:
#0 /var/www/html/vendor/mgp25/instagram-php/src/ImageAutoResizer.php(234): InstagramAPI\ImageAutoResizer->_shouldProcess()
#1 /var/www/html/vendor/mgp25/instagram-php/src/Utils.php(150): InstagramAPI\ImageAutoResizer->getFile()
#2 /var/www/html/vendor/mgp25/instagram-php/src/HttpInterface.php(732): InstagramAPI\Utils::createVideoIcon('./content/14739...')
#3 /var/www/html/vendor/mgp25/instagram-php/src/Instagram.php(816): InstagramAPI\HttpInterface->uploadPhotoData('timeline', './content/14739...', 'videofile', '1490054897561')
#4 /var/www/html/vendor/mgp25/instagram-php/src/Instagram.php(842): InstagramAPI\Instagram->_uploadVideo('timeline', './content/14739...', '\xD0\x9D\xD0\xB0\xD1\x81\xD1\x82\xD0\xBE\xD1\x8F\xD1\x89\xD0...', NULL, 10)
#5 /var/www/html/src/upload_new_publications.php(42): InstagramAPI\Instagram->uploadTimelineVideo('./content/14739. in /var/www/html/vendor/mgp25/instagram-php/src/ImageAutoResizer.php on line 268
```

---

### Describe my issue

Just updated via `composer update` to #7194f6f from #8f38bd8 commit. I realized that it would be the problem of _composer_ so I deleted lock file and vendor directory and reinstalled by executing `composer install` but no success.

**Comment by SteveJobzniak** [comment]
http://php.net/manual/en/exif.requirements.php

**Comment by SteveJobzniak** [comment]
I'll add some checks to make sure users have the required PHP libraries.

**Comment by SteveJobzniak** [comment]
https://github.com/mgp25/Instagram-API/commit/1e3bda0de8ae9d791e3588c5e9b7d9361201fab2
