### ISSUE TITLE
Upload problem with Api V3.0 [Other media configure error]

### ISSUE THREAD

**Issue by instagramlover** [mgp25/Instagram-API#1327]
i know there is another post talking about this problem but it was about V2 of this api , now this about v3

here is the log : 

```
POST:  upload/photo/
→ 245.81kB
← 200    46B
RESPONSE: {"upload_id": "1497403998146", "status": "ok"}

POST:  media/configure/
DATA: signed_body=81b9a6598234f1f19fd1c6d90ca81210570652bc81b446a2899f9f8e4d2761dc.{"device":{"manufacturer":"samsung","model":"SM-G935F","android_version":"23","android_release":"6.0.1"},"_csrftoken":"YUCyQ79FsmM7iLMwNc5PE9Wu4LU47MkJ","media_folder":"Camera","source_type":"4","_uid":"5459650662","_uuid":"3a85668e-a1e1-4c9b-8323-7c061464254e","edits":{"crop_original_size":[800,600],"crop_zoom":1,"crop_center":[0,0]},"extra":{"source_width":800,"source_height":600},"caption":"#pool #dreamresort #vacation #view","upload_id":"1497403998146"}&ig_sig_key_version=4
← 500    75B
RESPONSE: {"message": "Other media configure error: b'E3v4zLVnwi'", "status": "fail"}

upload#exception 'InstagramAPI\Exception\EndpointException' with message 'InstagramAPI\Response\ConfigureResponse: Other media configure error: b'E3v4zLVnwi'.' in /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:119
Stack trace:
#0 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Client.php(575): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'Other media con...', Object(InstagramAPI\Response\ConfigureResponse))
#1 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request.php(296): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\ConfigureResponse), Object(stdClass))
#2 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Internal.php(263): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\ConfigureResponse))
#3 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Internal.php(68): InstagramAPI\Request\Internal->configureSinglePhoto('timeline', Array, Array)
#4 /home/instagramlover/public_html/panel/libgram/vendor/mgp25/instagram-php/src/Request/Timeline.php(34): InstagramAPI\Request\Internal->uploadSinglePhoto('timeline', '/home/myinstara...', Array, Array)
#5 /home/instagramlover/public_html/panel/libgram/include/job.php(2049): InstagramAPI\Request\Timeline->uploadPhoto('/home/myinstara...', Array)
#6 /home/instagramlover/public_html/panel/libgram/include/job.php(161): Job->upload()
#7 /home/instagramlover/public_html/panel/libgram/worker.php(84): Job->startJob()
#8 [internal function]: sendWork('cb78d979799990d...')
#9 /home/instagramlover/public_html/panel/libgram/worker.php(13): call_user_func('sendWork', 'cb78d979799990d...')
#10 {main}
InstagramAPI\Response\ConfigureResponse: Other media configure error: b'E3v4zLVnwi'.

```

**Comment by mgp25** [comment]
Post here the image you are trying to upload

**Comment by mgp25** [comment]
@instagramlover with the image you posted: http://i.imgur.com/ZiuCTiz.jpg

I can upload and configure without any issue. Try retrying again later. I have even posted the same caption as you. Not an API issue. If you have a way to reproduce it, let me know, but so far works fine.

Remember that only local files are valid to be uploaded.

Regards

```json
POST:  media/configure/
DATA: signed_body=5799c1cba7594b53d2976da9b79da707e0a65042886fc0e1c38214a692d5ee10.{"device":{"manufacturer":"HUAWEI","model":"LON-L29","android_version":"24","android_release":"7.0"},"_csrftoken":"jBCalVuOVJfl53fB4u9ePOB3xQKSioj2","media_folder":"Camera","source_type":"4","_uid":"2057166221","_uuid":"ed66e738-5bcb-4770-95bc-0d08aae63864","edits":{"crop_original_size":[800,600],"crop_zoom":1,"crop_center":[0,0]},"extra":{"source_width":800,"source_height":600},"caption":"#pool #dreamresort #vacation #view","upload_id":"1497426747631"}&ig_sig_key_version=4

← 200 	 1.09kB
```

**Comment by instagramlover** [comment]
@mgp25 i got the error 
Please download this photo as it do not change anything in any photo program 
http://maximaart.com/3c468e32349ac576d6c78a2d3168b453__d61352b8d10c1e7935aec794157bcab2.jpg

the problem when any photo passed to the image fix ratio , it generate an image which not acceptable by instagram.

try this photo and you will see the error

**Comment by LanchaBasualdo** [comment]
I think Im getting the same error.
I have been sending many different media type from my phone via direct message to another account and downloading them in various ways using the `url` in `raven_media` to my computer.
Such ways are with functions:
`copy()`
`fopen()`
`file_put_content()`
Media is always downloaded with the same width and height and "quality" through all methods.
In every try to `uploadPhoto/Video()` im getting the error which says de minimum and maximum aspect ratio conditions are x an y but my media is 0.56 aspect ratio.
I have not checked if that is the real aspect ratio or not and I do not have my computer right know.
I hope this info helps. As soon as I lay hands on it again I'll present more information.
PS: last time I updated via composer was on monday. Running on osx mavick or higher. With brew ffmpeg, but I don't remember if ffprobe was installed with it.
Regards
