### ISSUE TITLE
JsonMapper still failing with dev-master

### ISSUE THREAD

**Issue by whitewallsaregreay** [mgp25/Instagram-API#1465]
## Prerequisites
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer completely.
- Put an `x` into all the boxes [ ] relevant to your issue (like so [x]).
- Use the *Preview* tab to see how your issue will actually look like, before sending it.
- Do not post screenshots of error messages or code.

---

### Before submitting an issue make sure you have:
- [x ] [Searched](https://github.com/mgp25/Instagram-API/search?type=Issues) the bugtracker for similar issues including **closed** ones
- [x ] [Read the FAQ](https://github.com/mgp25/Instagram-API/wiki/FAQ)
- [x ] [Read the wiki](https://github.com/mgp25/Instagram-API/wiki)
- [x ] [Reviewed the examples](https://github.com/mgp25/Instagram-API/tree/master/examples)
- [x ] [Installed the api using ``composer``](https://github.com/mgp25/Instagram-API#installation)

### Purpose of your issue?
- [x ] Bug report (encountered problems/errors)
- [ ] Feature request (request for new functionality)
- [ ] Question
- [ ] Other

---

### The following sections request more details for particular types of issues, you can remove any section (the contents between the triple ---) not applicable to your issue.

---

### For a *bug report*, you must include *code* that will replicate the error, and the *error log/traceback*.

Example Code:

```php
set_time_limit(0);
date_default_timezone_set('UTC');

require __DIR__.'/../vendor/autoload.php';

// Please provide your own code here, for example:

try {
    $debug = true;
    $ig = new \InstagramAPI\Instagram($debug);
    $ig->setUser('yourusername', 'yourpassword');
    $ig->login();
    $result = $ig->comment('14123451234567890_1234567890', "Hello World");
    var_dump($result);
} catch (\Exception $e) {
    echo $e->getMessage()."\n";
}
```
// It appears that specific user ID's are still causing the JsonMapper to fail
// Below are two IDs that generate the error.
$usersINFO = $ig->getUserInfoById( 39516342 )->user;
$usersINFO = $ig->getUserInfoById( 4067890921 )->user;

```php
// Please provide your error log/dump here, for example:

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'string' not found in C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php:550
Stack trace:
#0 C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php(382): JsonMapper-&gt;createInstance('string')
#1 C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php(265): JsonMapper-&gt;mapArray(Array, Array, 'string')
#2 C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php(280): JsonMapper-&gt;map(Object(stdClass), Object(InstagramAPI\Response\Model\User))
#3 C:\xampp\vendor\mgp25\instagram-php\src\Client.php(433): JsonMapper-&gt;map(Object(stdClass), Object(InstagramAPI\Response\UserInfoResponse))
#4 C:\xampp\vendor\mgp25\instagram-php\src\Request.php(105): InstagramAPI\Client-&gt;getMappedResponseObject(Object(InstagramAPI\Response\UserInfoResponse), Object(stdClass), true, NULL)
#5 C:\xampp\vendor\mgp25\instagram-php\src\Instagram.php(2310): InstagramAPI\Request-&gt;getResponse(Object(InstagramAPI\Response\UserInfoResponse))
#6 C:\xampp\htdocs\findFollowers.php(179): InstagramAPI\Instagram-&gt;getUser in <b>C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php</b> on line <b>550</b><br />
```

---

---

### Describe your issue

I've updated to the dev-master but I am still occasionally encountering 'Uncaught Error: Class 'string' not found in C:\xampp\vendor\netresearch\jsonmapper\src\JsonMapper.php:550'

I've been calling : 
$ig->getUserInfoById( $testID)->user;     // LINE A

in a loop and have noticed that the loop will run until it tried to get certain user IDs.  The source of the ID array ($testID) is simply from a hashtag search called earlier in my code: 

$hashTagFeed[$i]->user->pk

I get a response back when I run LINE A, but the fatal error occurs immediately after the OK response.

**Comment by szokeptr** [comment]
You can access properties on the response objects with the getX(), isX() methods (see [example](https://github.com/mgp25/Instagram-API/blob/master/examples/accessingValues.php)).
