### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by maxidon1** [mgp25/Instagram-API#1617]
Sorry for my bad english. I'll describe the problem with the code.
`$API = new \InstagramAPI\Instagram(false, false); `
`$API->login($some, $some); // $some - Arbitrary, maybe not right`
`try{`
`       var_dump($API->people->getSelfInfo());`
`    } catch (Exception $e) {`
`      echo $e->getMessage();`
` }`
In fact, in "catch" I process errors using "switch". But in this code, I can not get this error.

And return:

> Fatal error: Uncaught InstagramAPI\Exception\InvalidUserException: InstagramAPI\Response\LoginResponse: The username you entered doesn't appear to belong to an account. Please check your username and try again. in /var/www/user/data/www/domen/api/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php:151 Stack trace: #0 /var/www/user/data/www/domen/api/vendor/mgp25/instagram-php/src/Client.php(570): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'The username yo...', Object(InstagramAPI\Response\LoginResponse), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/user/data/www/domen/api/vendor/mgp25/instagram-php/src/Request.php(705): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\LoginResponse), Object(stdClass), Object(GuzzleHttp\Psr7\Response)) #2 /var/www/user/data/www/domen/api/vendor/mgp25/instagram-php/src/Instagram.php(399): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\LoginResponse)) #3 /var/www/user/data/www/domen in /var/www/user/data/www/domen/api/vendor/mgp25/instagram-php/src/Exception/ServerMessageThrower.php on line 151

I do not understand why the error does not come up with the help of "Try - Catch". 
I can not not receive these errors. Authorization can be made on the wrong login-password.
How to make handling such errors in "Try - Catch".

**Comment by maxidon1** [comment]
Found an error. The exception was not the request, but the authorization.
 `$ API-> login ($ some, $ some); `
Entering it into "Try-Catch", everything started working correctly.
