### ISSUE TITLE
like media

### ISSUE THREAD

**Issue by sbaikov96** [mgp25/Instagram-API#1681]
trying to put the like and produces an error

```
Fatal error:  Uncaught exception 'InstagramAPI\Exception\FeedbackRequiredException' with message 'InstagramAPI\Response\GenericResponse: Feedback required.' in D:\OpenServer\domains\test.ru\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php:151
Stack trace:
#0 D:\OpenServer\domains\test.ru\vendor\mgp25\instagram-php\src\Client.php(571): InstagramAPI\Exception\ServerMessageThrower::autoThrow('InstagramAPI\\Re...', 'feedback_requir...', Object(InstagramAPI\Response\GenericResponse), Object(GuzzleHttp\Psr7\Response))
#1 D:\OpenServer\domains\test.ru\vendor\mgp25\instagram-php\src\Request.php(668): InstagramAPI\Client->getMappedResponseObject(Object(InstagramAPI\Response\GenericResponse), Object(stdClass), Object(GuzzleHttp\Psr7\Response))
#2 D:\OpenServer\domains\test.ru\vendor\mgp25\instagram-php\src\Request\Media.php(178): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\GenericResponse))
#3 D:\OpenServer\domains\test.ru\i1ndex.php(28): InstagramAPI\Request\Media->like('163830438717532...')
#4 { in D:\OpenServer\domains\test.ru\vendor\mgp25\instagram-php\src\Exception\ServerMessageThrower.php on line 151
```

code

```
$username = '**';
  $password = '***';
  $debug = false;
  $truncatedDebug = false;
  //////////////////////
  $ig = new \InstagramAPI\Instagram($debug, $truncatedDebug);
  try {
      $ig->login($username, $password);
  } catch (Exception $e) {
    echo 'something went wrong '.$e->getMessage()."\n";
    exit(0);
  }

 $maxId= null;

do {
  $search = $ig->hashtag->getFeed('мивлгу', $maxId);

  foreach ($search->getItems() as $result){
    $find = R::find('parsing','media_id =?', array($result->getId())); 
    $find1 = R::find('out','media_id =?', array($result->getId())); 

    if ((count($find) <> 0) | count($find1)){
      echo "Соси";
    } else {
      $media = R::dispense('parsing');
      $media->media_id = $result->getId(); 
      $id = R::store($media);
      $maxId = $search->getNextMaxId();
    }
  }

} while($maxId !== null);
  ?>
```

on another machine this code runs fine

**Comment by mgp25** [comment]
The code you posted does not match with the exception you posted. You are obviously abusing the like function.

We don't support any spammer

Regards
