### ISSUE TITLE
people->getFollowing got Requested resource does not exist.

### ISSUE THREAD

**Issue by fericosali** [mgp25/Instagram-API#1738]
i run people-getFollowing and got result Requested resource does not exist.

```
PHP Fatal error:  Uncaught InstagramAPI\Exception\NotFoundException: Requested resource does not exist. in C:\xampp\htdocs\instagram_scraper\vendor\mgp25\instagram-php\src\Client.php:537
Stack trace:
#0 C:\xampp\htdocs\instagram_scraper\vendor\mgp25\instagram-php\src\Request.php(705): InstagramAPI\Client-getMappedResponseObject(Object(InstagramAPI\Response\FollowerAndFollowingResponse), NULL, Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\instagram_scraper\vendor\mgp25\instagram-php\src\Request\People.php(290): InstagramAPI\Request-getResponse(Object(InstagramAPI\Response\FollowerAndFollowingResponse))
#2 C:\xampp\htdocs\instagram_scraper\scraper.php(18): InstagramAPI\Request\People-getFollowing('4536825681')
#3 {main}
  thrown in C:\xampp\htdocs\instagram_scraper\vendor\mgp25\instagram-php\src\Client.php on line 537
```

my command is
```php
$ig-login('test123123asd', 'asdasdasd');
$rankToken = \InstagramAPI\Signatures::generateUUID();
$userId = $ig-people-getFollowing('4536825681');
```
this is my FollowerAndFollowingResponse
```php

<?php

namespace InstagramAPI\Response;

use InstagramAPI\AutoPropertyHandler;
use InstagramAPI\ResponseInterface;
use InstagramAPI\ResponseTrait;

/**
 * @method mixed getBigList()
 * @method string getNextMaxId()
 * @method mixed getPageSize()
 * @method Model\User[] getUsers()
 * @method bool isBigList()
 * @method bool isNextMaxId()
 * @method bool isPageSize()
 * @method bool isUsers()
 * @method setBigList(mixed $value)
 * @method setNextMaxId(string $value)
 * @method setPageSize(mixed $value)
 * @method setUsers(Model\User[] $value)
 */
class FollowerAndFollowingResponse extends AutoPropertyHandler implements ResponseInterface
{
        use ResponseTrait;
    
        /**
         * @var Model\User[]
         */
        public $users;
        /**
         * @var string
         */
        public $next_max_id;
        public $page_size;
        public $big_list;
    }


```
can someone help me?

**Comment by mgp25** [comment]
@fericosali wrong user ID, or user doesn't exist anymore.

Code is working perfectly.

Regards
