### ISSUE TITLE
PHP Fatal error:  Uncaught InstagramAPI

### ISSUE THREAD

**Issue by Mrp12** [mgp25/Instagram-API#2154]
```
PHP Fatal error:  Uncaught InstagramAPI\Exception\SettingsException: MySQL Error: PDO::prepare(): MySQL server has gone away in C:\xampp\htdocs\instacheeta\vendor
\mgp25\instagram-php\src\Settings\Storage\Components\PDOStorage.php:182
Stack trace:
#0 C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src\Settings\Storage\Components\PDOStorage.php(368): InstagramAPI\Settings\Storage\Components\PDOStorage->_setUserColumn('cookies',
 '[{"Name":"mid",...')
#1 C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src\Settings\StorageHandler.php(506): InstagramAPI\Settings\Storage\Components\PDOStorage->saveUserCookies('[{"Name":"mid",...')
#2 C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src\Client.php(318): InstagramAPI\Settings\StorageHandler->setCookies('[{"Name":"mid",...')
#3 C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src\Instagram.php(307): InstagramAPI\Client->saveCookieJar()
#4 C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src\Settings\StorageHandler.php(619): InstagramAPI\Instagram->Instagr in C:\xampp\htdocs\instacheeta\vendor\mgp25\instagram-php\src
\Settings\Storage\Components\PDOStorage.php on line 182


[Sat Aug 11 16:47:31 2018] PHP Stack trace:
[Sat Aug 11 16:47:31 2018] PHP   1. {main}() C:\xampp\htdocs\instacheeta\server.php:0
[Sat Aug 11 16:47:31 2018] PHP   2. require_once() C:\xampp\htdocs\instacheeta\server.php:21
[Sat Aug 11 16:47:31 2018] PHP   3. App\Http\Kernel->handle($request = *uninitialized*) C:\xampp\htdocs\instacheeta\public_html\index.php:55


[Sat Aug 11 16:47:31 2018] PHP   4. App\Http\Kernel->sendRequestThroughRouter($request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Foundation\Http
\Kernel.php:116
[Sat Aug 11 16:47:31 2018] PHP   5. Illuminate\Routing\Pipeline->then($destination = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Foundation\Http\Ker
nel.php:151
[Sat Aug 11 16:47:31 2018] PHP   6. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Pipeline\Pipeline.php:104
[Sat Aug 11 16:47:31 2018] PHP   7. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP   8. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\ve
ndor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP   9. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Foundation\Http\Middleware\CheckForMaintenanceMode.php:51
[Sat Aug 11 16:47:31 2018] PHP  10. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  11. Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\la
ravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  12. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Foundation\Http\Middleware\ValidatePostSize.php:27
[Sat Aug 11 16:47:31 2018] PHP  13. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  14. App\Http\Middleware\TrimStrings->handle($request = *uninitialized*, $next = *uninitialized*, ...$attributes = variadic()) C:\xampp\htdocs\instacheeta\ven
dor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  15. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Foundation\Http\Middleware\TransformsRequest.php:31
[Sat Aug 11 16:47:31 2018] PHP  16. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  17. Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle($request = *uninitialized*, $next = *uninitialized*, ...$attributes = variadic())
 C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  18. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Foundation\Http\Middleware\TransformsRequest.php:31
[Sat Aug 11 16:47:31 2018] PHP  19. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  20. App\Http\Middleware\TrustProxies->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Il
luminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  21. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\fideloper\proxy\src\TrustProxie
s.php:57
[Sat Aug 11 16:47:31 2018] PHP  22. App\Http\Kernel->Illuminate\Foundation\Http\{closure}($request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Rou
ting\Pipeline.php:30
[Sat Aug 11 16:47:31 2018] PHP  23. Illuminate\Routing\Router->dispatch($request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kerne
l.php:176
[Sat Aug 11 16:47:31 2018] PHP  24. Illuminate\Routing\Router->dispatchToRoute($request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Router
.php:597
[Sat Aug 11 16:47:31 2018] PHP  25. Illuminate\Routing\Router->runRoute($request = *uninitialized*, $route = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumi
nate\Routing\Router.php:608
[Sat Aug 11 16:47:31 2018] PHP  26. Illuminate\Routing\Router->runRouteWithinStack($route = *uninitialized*, $request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework
\src\Illuminate\Routing\Router.php:642
[Sat Aug 11 16:47:31 2018] PHP  27. Illuminate\Routing\Pipeline->then($destination = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Router.php:
667
[Sat Aug 11 16:47:31 2018] PHP  28. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Pipeline\Pipeline.php:104
[Sat Aug 11 16:47:31 2018] PHP  29. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  30. App\Http\Middleware\EncryptCookies->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\
Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  31. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Cookie\Middleware\EncryptCookies.php:59
[Sat Aug 11 16:47:31 2018] PHP  32. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  33. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\l
aravel\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  34. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
[Sat Aug 11 16:47:31 2018] PHP  35. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  36. Illuminate\Session\Middleware\StartSession->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framew
ork\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  37. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Session\Middleware\StartSession.php:63
[Sat Aug 11 16:47:31 2018] PHP  38. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  39. Illuminate\View\Middleware\ShareErrorsFromSession->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel
\framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  40. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\View\Middleware\ShareErrorsFromSession.php:49
[Sat Aug 11 16:47:31 2018] PHP  41. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  42. App\Http\Middleware\VerifyCsrfToken->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src
\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  43. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Foundation\Http\Middleware\VerifyCsrfToken.php:67
[Sat Aug 11 16:47:31 2018] PHP  44. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  45. Illuminate\Routing\Middleware\SubstituteBindings->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\
framework\src\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  46. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminat
e\Routing\Middleware\SubstituteBindings.php:41
[Sat Aug 11 16:47:31 2018] PHP  47. Illuminate\Routing\Pipeline->Illuminate\Pipeline\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illumina
te\Routing\Pipeline.php:53
[Sat Aug 11 16:47:31 2018] PHP  48. App\Http\Middleware\CheckUserActive->handle($request = *uninitialized*, $next = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src
\Illuminate\Pipeline\Pipeline.php:151
[Sat Aug 11 16:47:31 2018] PHP  49. Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}($passable = *uninitialized*) C:\xampp\htdocs\instacheeta\app\Http\Middleware\CheckUserActive.ph
p:24
[Sat Aug 11 16:47:31 2018] PHP  50. Illuminate\Routing\Router->Illuminate\Routing\{closure}($request = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\R
outing\Pipeline.php:30
[Sat Aug 11 16:47:31 2018] PHP  51. Illuminate\Routing\Route->run() C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Router.php:665
[Sat Aug 11 16:47:31 2018] PHP  52. Illuminate\Routing\Route->runController() C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
[Sat Aug 11 16:47:31 2018] PHP  53. Illuminate\Routing\ControllerDispatcher->dispatch($route = *uninitialized*, $controller = *uninitialized*, $method = *uninitialized*) C:\xampp\htdocs\ins
tacheeta\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
[Sat Aug 11 16:47:31 2018] PHP  54. App\Http\Controllers\InstagramController->callAction($method = *uninitialized*, $parameters = *uninitialized*) C:\xampp\htdocs\instacheeta\vendor\laravel
\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
[Sat Aug 11 16:47:31 2018] PHP  55. call_user_func_array:{C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54}(*uninitialized*, *uninitialized*) C:
\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
[Sat Aug 11 16:47:31 2018] PHP  56. App\Http\Controllers\InstagramController->check() C:\xampp\htdocs\instacheeta\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
[Sat Aug 11 16:47:31 2018] PHP  57. dd($var = *uninitialized*, ...$moreVars = variadic(*uninitialized*)) C:\xampp\htdocs\instacheeta\app\Http\Controllers\EndUser\InstagramController.php:256


```

**Comment by mgp25** [comment]
https://dev.mysql.com/doc/refman/8.0/en/gone-away.html
