### ISSUE TITLE
_sendLoginFlow causes Throttled by Instagram because of too many API requests

### ISSUE THREAD

**Issue by pussbb** [mgp25/Instagram-API#2941]
# Bug Report
After invoking  `finishTwoFactorLogin`  instead of successfull 2fa auth or not successfull you see
```plain
InstagramAPI\Exception\ThrottledException: Throttled by Instagram because of too many API requests. in app/vendor/mgp25/instagram-php/src/Client.php:681
Stack trace:
#0 app/vendor/mgp25/instagram-php/src/Client.php(737): InstagramAPI\Client->_guzzleRequest(Object(GuzzleHttp\Psr7\Request), Array)
#1 app/vendor/mgp25/instagram-php/src/Client.php(805): InstagramAPI\Client->_apiRequest(Object(GuzzleHttp\Psr7\Request), Array, Array)
#2 app/vendor/mgp25/instagram-php/src/Request.php(754): InstagramAPI\Client->api(Object(GuzzleHttp\Psr7\Request), Array)
#3 app/vendor/mgp25/instagram-php/src/Request.php(775): InstagramAPI\Request->getHttpResponse()
#4 app/vendor/mgp25/instagram-php/src/Request.php(831): InstagramAPI\Request->getRawResponse()
#5 app/vendor/mgp25/instagram-php/src/Request/Account.php(731): InstagramAPI\Request->getResponse(Object(InstagramAPI\Response\GenericResponse))
#6 app/vendor/mgp25/instagram-php/src/Instagram.php(1083): InstagramAPI\Request\Account->getProcessContactPointSignals()
#7 app/vendor/mgp25/instagram-php/src/Instagram.php(607): InstagramAPI\Instagram->_sendLoginFlow(true, 1800)
#8 app/src/Api/Challenges/SimpleChallenge.php(89): InstagramAPI\Instagram->finishTwoFactorLogin('USER', 'PASSWORD', 'IDETIFIER', 'CODE')
```
From backtrace it seems that riched ``_sendLoginFlow`` I assume we passed 2fa auth .
So the question is we really need all that things in _sendLoginFlow ?

```php
if ($justLoggedIn) {
            // Reset zero rating rewrite rules.
            $this->client->zeroRating()->reset();
            // Perform the "user has just done a full login" API flow.
            $this->account->getAccountFamily();
            $this->internal->sendLauncherSync(false, false, true);
            $this->internal->fetchZeroRatingToken();
            $this->internal->syncUserFeatures();
            $this->timeline->getTimelineFeed();
            $this->story->getReelsTrayFeed('cold_start');
            $this->internal->sendLauncherSync(false, false, true, true);
            $this->story->getReelsMediaFeed($this->account_id);
            $this->people->getRecentActivityInbox();
            //TODO: Figure out why this isn't sending...
//            $this->internal->logResurrectAttribution();
            $this->internal->getLoomFetchConfig();
            $this->internal->getDeviceCapabilitiesDecisions();
            $this->people->getBootstrapUsers();
            $this->people->getInfoById($this->account_id);
            $this->account->getLinkageStatus();
            $this->creative->sendSupportedCapabilities();
            $this->media->getBlockedMedia();
            $this->internal->storeClientPushPermissions();
            $this->internal->getQPCooldowns();
            $this->_registerPushChannels();
            $this->story->getReelsMediaFeed($this->account_id);
            $this->discover->getExploreFeed(null, null, true);
            $this->internal->getQPFetch();
            $this->account->getProcessContactPointSignals();
            $this->internal->getArlinkDownloadInfo();
            $this->_registerPushChannels();
            $this->people->getSharePrefill();
            $this->direct->getPresences();
            $this->direct->getInbox();
            $this->direct->getInbox(null, 20, 10);
            $this->_registerPushChannels();
            $this->internal->getFacebookOTA();
```

Instgram blocks
```php
$this->account->getProcessContactPointSignals();
```
its 28-th method/request from 36 . 

Also 
```php
 $this->direct->getInbox();
            $this->direct->getInbox(null, 20, 10);
```
would not be better  simply 
```php
 $this->direct->getInbox(null, 20, 10);
```

Instagram version API is
```json
  "name": "mgp25/instagram-php",
  "version": "v7.0.1",
```

**Comment by geekshetty** [comment]
can anybody please tell me how to fix this? even I'm facing same problem even after updating latest updated code..

**Comment by pussbb** [comment]
well it seems that ignore ``ThrottledException``  is a temprorary solution that is working. 
```php
try {
    $loginResponse =  $this->api->login($this->username, $this->password);
    ....
} catch (\Throwable $throwable) {
    if ($throwable instanceof ThrottledException && $this->api->account_id) {
        $this->state = self::AUTHORIZED;
        return null;
    }
}
```

and 
```php
try {
            $this->api->finishTwoFactorLogin(
                $this->api->username, 
                $this->api->password,
                $this->info->getTwoFactorInfo()->getTwoFactorIdentifier(),
                trim($code)
            );
        } catch (ThrottledException $exception) {
            $this->logger->debug($exception);
        }
```

at least for now its working and does not harm for further usage.

**Comment by wavepacket0** [comment]
the only think that worked for me was adding a random delay using sleep, [0.2, 0.9] seconds, between the many function calls in the preloginflow and postloginflow functions

**Comment by Juan-de-Costa-Rica** [comment]
So here is a packet capture with times from a real login I did tonight with times so you can see how the real app works.

Note that this is from app version 35.0.0.20.96, so it's a bit old, but could still be useful reference info for some.

Also note I had a suspicious activity checkpoint I solved  via SMS code.

```
#01	19:08:27	POST /api/v1/accounts/read_msisdn_header/

#02	19:08:27	POST /api/v1/attribution/log_attribution/

#03	19:08:27	POST /api/v1/accounts/contact_point_prefill/ 

#04	19:08:27	POST /api/v1/qe/sync/ 

#05	19:08:58	POST /api/v1/accounts/contact_point_prefill/ 

#06 	19:09:12	POST /api/v1/accounts/login/
			GET /api/v1/challenge/330592117/V9hRMJ523S/?guid=9419974c-3663-4a29-a46c-599968b8ba81&device_id=android-83cc598b958f665b

#07	19:09:26	POST /api/v1/challenge/330592117/V9hRMJ523S/

#08 	19:09:41	POST /api/v1/challenge/330592117/V9hRMJ523S/
			** LOGIN SUCCESSFUL RESPONSE **
			POST /api/v1/qe/sync/

#09	19:09:45	GET /api/v1/zr/token/result/?device_id=android-83cc598b958f665b&token_hash=&custom_device_id=9419974c-3663-4a29-a46c-599968b8ba81
			POST /api/v1/feed/reels_tray/ 

#10	19:09:45	{MQTT DATA}

#11	19:09:46	POST /api/v1/feed/timeline/

#12	19:09:46	{NO DATA}

#13	19:09:46	{10 GET Requests, first is my profile photo, others are photos sent to me in direct messages}

#14	19:09:46	{NO DATA}

#15	19:09:46	{NO DATA}

#16	19:09:46	{NO DATA}

#17	19:09:46	{NO DATA}

#18	19:09:47	POST /api/v1/accounts/log_acquirable_phone_number/
			POST /api/v1/feed/reels_media/
			GET /api/v1/direct_v2/inbox/?visual_message_return_type=unseen&persistentBadging=true&use_unified_inbox=true 
			GET /api/v1/media/blocked/

#19	19:09:47	GET /api/v1/direct_v2/ranked_recipients/?mode=reshare&show_threads=true&use_unified_inbox=true
			POST /api/v1/accounts/read_msisdn_header/
			GET /api/v1/scores/bootstrap/users/?surfaces=%5B%22autocomplete_user_list%22%2C%22coefficient_rank_recipient_user_suggestion%22%2C%22coefficient_ios_section_test_bootstrap_ranking%22%2C%22coefficient_direct_recipients_ranking_variant_2%22%2C%22coefficient_direct_recipients_ranking%22%5D 
​			GET /api/v1/facebook_ota/?fields=update%257Bdownload_uri%252Cdownload_uri_delta_base%252Cversion_code_delta_base%252Cdownload_uri_delta%252Cfallback_to_full_update%252Cfile_size_delta%252Cversion_code%252Cpublished_date%252Cfile_size%252Cota_bundle_type%252Cresources_checksum%257D&custom_user_id=330592117&signed_body=1c1d9a4fb0fbb06fe48e6f00317a6c1bb23d0cd4b229ec7cec880b155ad2f077.&ig_sig_key_version=4&version_code=95414346&version_name=35.0.0.20.96&custom_app_id=124024574287414&custom_device_id=9419974c-3663-4a29-a46c-599968b8ba81

#20	19:09:47	POST /api/v1/push/register/
			POST /api/v1/qp/fetch/
			GET /api/v1/discover/explore/?is_prefetch=true&timezone_offset=-21600&session_id=c3e01f18-0433-4d8e-947c-67e9cde428fd

#21	19:09:47	GET /api/v1/direct_v2/ranked_recipients/?mode=raven&show_threads=true&use_unified_inbox=true 
			GET /api/v1/users/profile_notice/
			POST /api/v1/push/register/

#22	19:09:47	{18 GET Requests of .jpg and .mp4 files, the discover/explore feed I think}

#23	19:09:47	{2 GET Requests, .jpgs}

#24	19:09:47	(2 GET Requests, .jpgs - last one was a photo I had sent as a direct message)

#25	19:09:47	GET /api/v1/news/inbox/
```

**Comment by sergeykomlev** [comment]
@wavepacket0, you did it between every functions? 

The problem arises from time to time, I don’t really understand what began to cause it, do pauses really help?

**Comment by kicks66** [comment]
> well it seems that ignore `ThrottledException` is a temprorary solution that is working.
> 
> ```
> try {
>     $loginResponse =  $this->api->login($this->username, $this->password);
>     ....
> } catch (\Throwable $throwable) {
>     if ($throwable instanceof ThrottledException && $this->api->account_id) {
>         $this->state = self::AUTHORIZED;
>         return null;
>     }
> }
> ```
> 
> and
> 
> ```
> try {
>             $this->api->finishTwoFactorLogin(
>                 $this->api->username, 
>                 $this->api->password,
>                 $this->info->getTwoFactorInfo()->getTwoFactorIdentifier(),
>                 trim($code)
>             );
>         } catch (ThrottledException $exception) {
>             $this->logger->debug($exception);
>         }
> ```
> 
> at least for now its working and does not harm for further usage.

This solution doesnt allow a login to occur though? It just catches the error - am I correct in thinking?

**Comment by sergeykomlev** [comment]
@kicks66, this is not a good solution and not good way to handle throttled exception. 

For me work this logic:
1. Comment line with getProcessContactPointSignals().
2. Add sleep(1) between getInbox() function calls.
