### ISSUE TITLE
Uncaught Error: Call to a member function request() on null

### ISSUE THREAD

**Issue by hippich** [mgp25/Instagram-API#669]
Just updated to latest dev version and got this while trying to login:

```
PHP Fatal error:  Uncaught Error: Call to a member function request() on null in vendor/mgp25/instagram-php/src/Instagram.php:1769
Stack trace:
#0 vendor/mgp25/instagram-php/src/Instagram.php(211): InstagramAPI\Request->getResponse(Object(InstagramAPI\SyncResponse))
#1 vendor/mgp25/instagram-php/src/Instagram.php(131): InstagramAPI\Instagram->syncFeatures(true)
#2 rss2instagram.php(14): InstagramAPI\Instagram->login()
#3 {main}
  thrown in vendor/mgp25/instagram-php/src/Instagram.php on line 1769
```

PHP version:
```
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by mgp25** [comment]
@wukerplank run the following command `composer update`

**Comment by hippich** [comment]
There is no debug log, just that exception right away. Here is complete terminal output:

```
$ php igtest.php truarthq Qwerty123
PHP Fatal error:  Uncaught Error: Call to a member function request() on null in /vendor/mgp25/instagram-php/src/Instagram.php:1769
Stack trace:
#0 /vendor/mgp25/instagram-php/src/Instagram.php(211): InstagramAPI\Request->getResponse(Object(InstagramAPI\SyncResponse))
#1 /vendor/mgp25/instagram-php/src/Instagram.php(131): InstagramAPI\Instagram->syncFeatures(true)
#2 /igtest.php(10): InstagramAPI\Instagram->login()
#3 {main}
  thrown in /vendor/mgp25/instagram-php/src/Instagram.php on line 1769
```

Here is test script:

```
<?php
require("./vendor/autoload.php");

$username = $argv[1];
$password = $argv[2];

$insta = new \InstagramAPI\Instagram($username, $password, true);

try {
    $insta->login();
} catch (Exception $e) {
    $e->getMessage();
    exit(1);
}
```

I updated instagram-api package via:

```
composer require mgp25/instagram-php dev-master
```

**Comment by mgp25** [comment]
@hippich the constructor has changes. you need to do this:

```php
$debug = true;
$insta = new \InstagramAPI\Instagram($debug);
$insta->setUser($username, $password);

...
```

Let me know of that worked

**Comment by hippich** [comment]
Yeah, it worked. Sorry, missed change in API usage. And thanks!
